#spring.application.name=sistemas-reservas
## YAML Template.
---
spring:
  datasource:
    url: jdbc:postgresql://c8lj070d5ubs83.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/dfiplaleo1sco2
    username: ude8rqu210j3m8
    password: p69bc29dddbe5ff4cc7a9e79a6a59fd87c200913041b679f7fc3018663be6009c
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: gestionreservasupc@gmail.com
    password: uuvu wfnj wqgj hjsp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true