## YAML Template.
---
spring:
  datasource:
    # This line uses the DATABASE_URL environment variable set by Heroku, falling back to a local DB URL if not available
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/Laboratory}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME:postgres}   # Heroku sets this
    password: ${JDBC_DATABASE_PASSWORD:guntersitoSQL}   # Heroku sets this

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: laboratoristaupc@gmail.com
    password: ezim tduj kezy gzld
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true